import {
  ThemeSettings,
  FieldVisibilityConfig,
  SkuBarcodeSettings,
  EnhancedPrintSettings,
  CustomFieldDefinition,
  PaymentMethodItem,
  ExpenseCategoryItem,
  TaxDiscountSettings,
  UserRoleDefinition,
  LocalizationSettings,
  NotificationSettings,
  SecuritySettings,
  DashboardChartConfig,
  DashboardWidgetConfig,
  DashboardQuickItemConfig,
  DashboardMetricConfig,
  DashboardCustomSettings,
  BusinessSetupConfig,
  BrandItem,
  CategoryItem,
  UnitItem,
  ProductTypeItem,
  ProductStatusItem,
  TaxTypeItem,
  DiscountTypeItem,
  PriceTypeItem,
  IncomeCategoryItem,
  CustomerTypeItem,
  SupplierTypeItem,
  SalesTypeItem,
  PurchaseTypeItem,
  TopIconMenuConfig,
  TopIconMenuItem,
} from '../types';

export const DEFAULT_THEME_SETTINGS: ThemeSettings = {
  mode: 'light',
  primaryColor: 'emerald',
  fontFamily: 'Plus_Jakarta_Sans',
  textSize: 'medium',
  borderRadius: '2xl',
  sidebarStyle: 'default',
  headerStyle: 'default',
  cardStyle: 'bordered',
};

export const DEFAULT_DASHBOARD_QUICK_ITEMS: DashboardQuickItemConfig[] = [
  { id: 'sales', label: 'নতুন বিক্রয়', iconName: 'Receipt', tab: 'sales', color: 'bg-blue-600', enabled: true, order: 1 },
  { id: 'purchases', label: 'নতুন ক্রয়', iconName: 'Truck', tab: 'purchases', color: 'bg-emerald-600', enabled: true, order: 2 },
  { id: 'customers', label: 'কাস্টমার', iconName: 'Users', tab: 'customers', color: 'bg-fuchsia-600', enabled: true, order: 3 },
  { id: 'products', label: 'পণ্য তালিকা', iconName: 'Package', tab: 'products', color: 'bg-orange-500', enabled: true, order: 4 },
  { id: 'pos', label: 'POS / বিলিং', iconName: 'ShoppingCart', tab: 'pos', color: 'bg-amber-500', enabled: true, order: 5 },
  { id: 'suppliers', label: 'সাপ্লায়ার', iconName: 'Building2', tab: 'suppliers', color: 'bg-indigo-600', enabled: true, order: 6 },
  { id: 'payments', label: 'পেমেন্ট জমা', iconName: 'ArrowLeftRight', tab: 'payments', color: 'bg-sky-600', enabled: true, order: 7 },
  { id: 'expenses', label: 'দৈনিক খরচ', iconName: 'DollarSign', tab: 'expenses', color: 'bg-rose-500', enabled: true, order: 8 },
  { id: 'inventory', label: 'মজুদ স্টক', iconName: 'Boxes', tab: 'inventory', color: 'bg-teal-600', enabled: false, order: 9 },
  { id: 'reports', label: 'রিপোর্ট সেন্টার', iconName: 'FileBarChart', tab: 'reports', color: 'bg-red-600', enabled: false, order: 10 },
  { id: 'accounting', label: 'হিসাব খাতা', iconName: 'Scale', tab: 'accounting', color: 'bg-violet-600', enabled: false, order: 11 },
  { id: 'hr', label: 'কর্মী / বেতন', iconName: 'UserCheck', tab: 'hr', color: 'bg-cyan-600', enabled: false, order: 12 },
  { id: 'delivery', label: 'ডেলিভারি', iconName: 'Truck', tab: 'delivery', color: 'bg-lime-600', enabled: false, order: 13 },
];

export const DEFAULT_DASHBOARD_METRICS_CONFIG: DashboardMetricConfig[] = [
  { id: 'totalDue', label: 'মোট বাকি (Receivable)', category: 'all_time', iconName: 'AlertCircle', color: 'text-amber-700', enabled: true, order: 1 },
  { id: 'cashInHand', label: 'নগদ টাকা (Cash In Hand)', category: 'all_time', iconName: 'Wallet', color: 'text-emerald-700', enabled: true, order: 2 },
  { id: 'totalSales', label: 'মোট বিক্রয় (Total Sales)', category: 'all_time', iconName: 'TrendingUp', color: 'text-slate-900', enabled: true, order: 3 },
  { id: 'totalPurchases', label: 'মোট ক্রয় (Total Purchase)', category: 'all_time', iconName: 'ShoppingBag', color: 'text-slate-900', enabled: true, order: 4 },
  { id: 'todaySales', label: 'আজকের বিক্রয়', category: 'today', iconName: 'Receipt', color: 'text-slate-900', enabled: true, order: 5 },
  { id: 'todayPurchase', label: 'আজকের ক্রয়', category: 'today', iconName: 'Truck', color: 'text-slate-900', enabled: true, order: 6 },
  { id: 'todayReceived', label: 'আজকের জমা (Collection)', category: 'today', iconName: 'ArrowDownLeft', color: 'text-emerald-700', enabled: true, order: 7 },
  { id: 'todayDue', label: 'আজকের বাকি (New Due)', category: 'today', iconName: 'Clock', color: 'text-rose-700', enabled: true, order: 8 },
  { id: 'bankBalance', label: 'ব্যাংক ব্যালেন্স', category: 'all_time', iconName: 'Landmark', color: 'text-blue-700', enabled: true, order: 9 },
  { id: 'mobileBanking', label: 'মোবাইল ব্যাংকিং', category: 'all_time', iconName: 'Smartphone', color: 'text-purple-700', enabled: true, order: 10 },
  { id: 'netProfit', label: 'নিট লাভ (Net Profit)', category: 'all_time', iconName: 'DollarSign', color: 'text-emerald-700', enabled: true, order: 11 },
  { id: 'totalExpense', label: 'মোট খরচ (Total Expense)', category: 'all_time', iconName: 'ArrowUpRight', color: 'text-rose-700', enabled: true, order: 12 },
  { id: 'stockValue', label: 'মজুদ স্টক মূল্য', category: 'all_time', iconName: 'Package', color: 'text-teal-700', enabled: true, order: 13 },
  { id: 'supplierPayable', label: 'মহাজন দেনা (Payable)', category: 'all_time', iconName: 'Building2', color: 'text-purple-700', enabled: true, order: 14 },
  { id: 'todayExpense', label: 'আজকের খরচ', category: 'today', iconName: 'DollarSign', color: 'text-rose-700', enabled: true, order: 15 },
];

export const DEFAULT_DASHBOARD_CHARTS: DashboardChartConfig[] = [
  { id: 'salesChart', label: 'বিক্রয় ও রাজস্ব চার্ট (Sales Trend)', enabled: true, order: 1 },
  { id: 'purchaseChart', label: 'ক্রয় চার্ট (Purchase Trend)', enabled: true, order: 2 },
  { id: 'expenseChart', label: 'মাসিক খরচ বিশ্লেষণ (Expense Breakdown)', enabled: true, order: 3 },
  { id: 'profitChart', label: 'লাভ-ক্ষতি ও মার্জিন চার্ট (Profit Margin)', enabled: true, order: 4 },
];

export const DEFAULT_DASHBOARD_WIDGETS: DashboardWidgetConfig[] = [
  { id: 'recentSales', label: 'সাম্প্রতিক বিক্রয় তালিকা (Recent Invoices)', enabled: true, order: 1 },
  { id: 'recentPurchases', label: 'সাম্প্রতিক ক্রয় তালিকা (Recent Purchases)', enabled: true, order: 2 },
  { id: 'recentPayments', label: 'সাম্প্রতিক পেমেন্ট কালেকশন (Recent Payments)', enabled: true, order: 3 },
  { id: 'recentExpenses', label: 'সাম্প্রতিক খরচ তালিকা (Recent Expenses)', enabled: true, order: 4 },
  { id: 'topProducts', label: 'শীর্ষ বিক্রিত পণ্যসমূহ (Top Selling Products)', enabled: true, order: 5 },
  { id: 'topCustomers', label: 'প্রধান গ্রাহক তালিকা (Top VIP Customers)', enabled: true, order: 6 },
  { id: 'lowStockAlerts', label: 'স্বল্প স্টক সতর্কতা (Low Stock Alerts)', enabled: true, order: 7 },
  { id: 'salesSummary', label: 'মাসিক ব্যবসায়িক সামারি (Monthly Summary)', enabled: true, order: 8 },
];

export const DEFAULT_DASHBOARD_CUSTOM_SETTINGS: DashboardCustomSettings = {
  quickItems: DEFAULT_DASHBOARD_QUICK_ITEMS,
  metrics: DEFAULT_DASHBOARD_METRICS_CONFIG,
  charts: DEFAULT_DASHBOARD_CHARTS,
  widgets: DEFAULT_DASHBOARD_WIDGETS,
  cardSize: 'standard',
};

// Product Fields
export const DEFAULT_PRODUCT_FIELDS: FieldVisibilityConfig[] = [
  { id: 'name', label: 'পণ্যের নাম (Product Name)', show: true, required: true, order: 1 },
  { id: 'sku', label: 'SKU কোড (SKU Code)', show: true, required: false, order: 2 },
  { id: 'barcode', label: 'বারকোড (Barcode)', show: true, required: false, order: 3 },
  { id: 'category', label: 'ক্যাটাগরি (Category)', show: true, required: true, order: 4 },
  { id: 'brand', label: 'ব্র্যান্ড (Brand)', show: true, required: false, order: 5 },
  { id: 'unit', label: 'একক (Unit Type)', show: true, required: true, order: 6 },
  { id: 'purchasePrice', label: 'ক্রয় মূল্য (Purchase Price)', show: true, required: true, order: 7 },
  { id: 'salePrice', label: 'বিক্রয় মূল্য (Selling Price)', show: true, required: true, order: 8 },
  { id: 'mrp', label: 'পাইকারি / MRP মূল্য', show: true, required: false, order: 9 },
  { id: 'taxPercent', label: 'ট্যাক্স / ভ্যাট %', show: true, required: false, order: 10 },
  { id: 'discountPercent', label: 'ডিফল্ট ডিসকাউন্ট %', show: true, required: false, order: 11 },
  { id: 'openingStock', label: 'প্রাথমিক স্টক (Current Stock)', show: true, required: false, order: 12 },
  { id: 'minStock', label: 'ন্যূনতম স্টক সতর্কতা (Low Stock Limit)', show: true, required: false, order: 13 },
  { id: 'warehouse', label: 'গোডাউন / ওয়্যারহাউজ', show: true, required: false, order: 14 },
  { id: 'photo', label: 'পণ্যের ছবি (Product Image)', show: true, required: false, order: 15 },
  { id: 'batchNo', label: 'ব্যাচ নম্বর (Batch No)', show: true, required: false, order: 16 },
  { id: 'expDate', label: 'মেয়াদ উত্তীর্ণের তারিখ (Exp Date)', show: true, required: false, order: 17 },
  { id: 'description', label: 'বিবরণ / নোটস', show: true, required: false, order: 18 },
];

// Customer Fields
export const DEFAULT_CUSTOMER_FIELDS: FieldVisibilityConfig[] = [
  { id: 'name', label: 'কাস্টমারের নাম (Customer Name)', show: true, required: true, order: 1 },
  { id: 'phone', label: 'মোবাইল নম্বর (Phone Number)', show: true, required: true, order: 2 },
  { id: 'email', label: 'ইমেইল (Email Address)', show: true, required: false, order: 3 },
  { id: 'address', label: 'ঠিকানা (Address)', show: true, required: false, order: 4 },
  { id: 'companyName', label: 'দোকান বা ব্যবসা প্রতিষ্ঠান (Shop/Company)', show: true, required: false, order: 5 },
  { id: 'photo', label: 'কাস্টমার ছবি (Photo)', show: true, required: false, order: 6 },
  { id: 'openingBalance', label: 'পূর্বের বাকি (Opening Due)', show: true, required: false, order: 7 },
  { id: 'creditLimit', label: 'বাকি নেওয়ার সর্বোচ্চ সীমা (Credit Limit)', show: true, required: false, order: 8 },
  { id: 'notes', label: 'মন্তব্য / স্পেশাল নোট', show: true, required: false, order: 9 },
];

// Supplier Fields
export const DEFAULT_SUPPLIER_FIELDS: FieldVisibilityConfig[] = [
  { id: 'name', label: 'সাপ্লায়ার / মহাজন নাম (Supplier Name)', show: true, required: true, order: 1 },
  { id: 'phone', label: 'মোবাইল নম্বর (Phone)', show: true, required: true, order: 2 },
  { id: 'email', label: 'ইমেইল (Email)', show: true, required: false, order: 3 },
  { id: 'address', label: 'ঠিকানা ও অফিস (Address)', show: true, required: false, order: 4 },
  { id: 'openingBalance', label: 'পূর্বের পাওনা (Opening Balance)', show: true, required: false, order: 5 },
  { id: 'creditLimit', label: 'ক্রেডিট লিমিট (Credit Limit)', show: true, required: false, order: 6 },
  { id: 'notes', label: 'নোটস (Notes)', show: true, required: false, order: 7 },
];

// Sales Fields
export const DEFAULT_SALES_FIELDS: FieldVisibilityConfig[] = [
  { id: 'invoiceNo', label: 'চালান নং (Invoice No)', show: true, required: true, order: 1 },
  { id: 'date', label: 'তারিখ ও সময় (Date & Time)', show: true, required: true, order: 2 },
  { id: 'customer', label: 'কাস্টমার নির্বাচন (Customer)', show: true, required: true, order: 3 },
  { id: 'items', label: 'পণ্য তালিকা ও পরিমাণ (Items & Qty)', show: true, required: true, order: 4 },
  { id: 'sku', label: 'SKU কোড ফিল্ড', show: true, required: false, order: 5 },
  { id: 'barcode', label: 'বারকোড স্ক্যানার ফিল্ড', show: true, required: false, order: 6 },
  { id: 'discount', label: 'ছাড় / ডিসকাউন্ট (Discount)', show: true, required: false, order: 7 },
  { id: 'tax', label: 'ভ্যাট / ট্যাক্স (VAT/Tax)', show: true, required: false, order: 8 },
  { id: 'deliveryCharge', label: 'ডেলিভারি বা পরিবহন চার্জ', show: true, required: false, order: 9 },
  { id: 'paidAmount', label: 'জমা টাকা (Paid Amount)', show: true, required: false, order: 10 },
  { id: 'dueAmount', label: 'বকেয়া টাকা (Due Amount)', show: true, required: false, order: 11 },
  { id: 'paymentMethod', label: 'পেমেন্ট মেথড (Payment Method)', show: true, required: true, order: 12 },
  { id: 'salesman', label: 'বিক্রয়কর্মী (Salesman / User)', show: true, required: false, order: 13 },
  { id: 'notes', label: 'চালানের নোটস / শর্তাবলী', show: true, required: false, order: 14 },
];

// Purchase Fields
export const DEFAULT_PURCHASE_FIELDS: FieldVisibilityConfig[] = [
  { id: 'billNo', label: 'বিল / ইনভয়েস নং (Bill No)', show: true, required: true, order: 1 },
  { id: 'date', label: 'ক্রয়ের তারিখ (Date)', show: true, required: true, order: 2 },
  { id: 'supplier', label: 'সাপ্লায়ার / মহাজন (Supplier)', show: true, required: true, order: 3 },
  { id: 'items', label: 'ক্রয়কৃত পণ্য ও রেট', show: true, required: true, order: 4 },
  { id: 'discount', label: 'সাপ্লায়ার ডিসকাউন্ট', show: true, required: false, order: 5 },
  { id: 'tax', label: 'ট্যাক্স / ভ্যাট', show: true, required: false, order: 6 },
  { id: 'additionalCharge', label: 'অতিরিক্ত পরিবহন ও কুলি খরচ', show: true, required: false, order: 7 },
  { id: 'paidAmount', label: 'পরিশোধিত টাকা (Paid)', show: true, required: false, order: 8 },
  { id: 'dueAmount', label: 'বকেয়া দেনা (Due)', show: true, required: false, order: 9 },
  { id: 'paymentMethod', label: 'পেমেন্ট মাধ্যম', show: true, required: true, order: 10 },
  { id: 'notes', label: 'ক্রয় সংক্রান্ত নোটস', show: true, required: false, order: 11 },
];

// Expense Fields
export const DEFAULT_EXPENSE_FIELDS: FieldVisibilityConfig[] = [
  { id: 'expenseNo', label: 'ভাউচার নং (Expense Voucher No)', show: true, required: true, order: 1 },
  { id: 'category', label: 'খরচের খাত (Expense Category)', show: true, required: true, order: 2 },
  { id: 'amount', label: 'টাকার পরিমাণ (Amount)', show: true, required: true, order: 3 },
  { id: 'date', label: 'তারিখ (Date)', show: true, required: true, order: 4 },
  { id: 'paymentMethod', label: 'পেমেন্ট মাধ্যম', show: true, required: true, order: 5 },
  { id: 'paidBy', label: 'কে পরিশোধ করেছে (Company/Owner)', show: true, required: false, order: 6 },
  { id: 'description', label: 'খরচের বিস্তারিত বিবরণ', show: true, required: false, order: 7 },
];

// SKU & Barcode Settings
export const DEFAULT_SKU_BARCODE_SETTINGS: SkuBarcodeSettings = {
  autoSku: true,
  skuPrefix: 'PRD-',
  autoBarcode: true,
  barcodeType: 'CODE128',
  showSkuInTables: true,
  showBarcodeInTables: true,
};

// Enhanced Print Settings
export const DEFAULT_ENHANCED_PRINT_SETTINGS: EnhancedPrintSettings = {
  paperSize: 'a4',
  printTheme: 'modern',
  customWidthMm: 210,
  customHeightMm: 297,
  marginTopMm: 10,
  marginBottomMm: 10,
  marginLeftMm: 10,
  marginRightMm: 10,
  headerHeightMm: 35,
  footerHeightMm: 25,
  fontSizePt: 10,
  logoSize: 'medium',
  logoPosition: 'left',
  textAlignment: 'left',
  showLogo: true,
  showCompanyName: true,
  showAddress: true,
  showPhone: true,
  showEmail: true,
  showPreviousBalance: true,
  showReceived: true,
  showTotalBalance: true,
  showTotalDue: true,
  showInvoiceNo: true,
  showDate: true,
  showCustomerInfo: true,
  showCustomerPhoto: true,
  showItemPhoto: true,
  showItemSku: true,
  showItemBarcode: true,
  showItemQrCode: false,
  showItemDiscount: true,
  showItemTax: false,
  showVatBin: true,
  showSignatureLines: true,
  showNotes: true,
  showTermsConditions: true,
  termsConditionsText: '১. বিক্রিত পণ্য ৭ দিনের মধ্যে ক্যাশ মেমোসহ পরিবর্তনযোগ্য।\n২. কোনো অবস্থাতেই ক্যাশ ফেরত দেওয়া হয় না।\n৩. চেক পেমেন্টের ক্ষেত্রে চেক পাস হওয়া সাপেক্ষে জমা কার্যকর হবে।',
  showPaymentMethod: true,
  receiptFooterNote: 'ধন্যবাদ! আমাদের সাথে ব্যবসা করার জন্য আমরা আন্তরিকভাবে কৃতজ্ঞ। আবার আসবেন!',
};

// Payment Methods
export const DEFAULT_PAYMENT_METHODS: PaymentMethodItem[] = [
  { id: 'pay_cash', name: 'নগদ ক্যাশ (Cash in Hand)', type: 'cash', enabled: true, isDefault: true, order: 1 },
  { id: 'pay_bkash', name: 'বিকাশ মার্চেন্ট / পার্সোনাল (bKash)', type: 'mobile_banking', accountNumber: '01819-876543 (Merchant)', enabled: true, isDefault: false, order: 2 },
  { id: 'pay_nagad', name: 'নগদ (Nagad Wallet)', type: 'mobile_banking', accountNumber: '01711-234567', enabled: true, isDefault: false, order: 3 },
  { id: 'pay_rocket', name: 'রকেট (DBBL Rocket)', type: 'mobile_banking', accountNumber: '01711-234567-8', enabled: true, isDefault: false, order: 4 },
  { id: 'pay_bank_islami', name: 'ইসলামী ব্যাংক বাংলাদেশ লিঃ (IBBL)', type: 'bank', bankName: 'Islami Bank', accountNumber: '2050-12345678901', enabled: true, isDefault: false, order: 5 },
  { id: 'pay_bank_city', name: 'দি সিটি ব্যাংক লিঃ (City Bank)', type: 'bank', bankName: 'City Bank', accountNumber: '1102-987654321', enabled: true, isDefault: false, order: 6 },
  { id: 'pay_card', name: 'POS কার্ড পেমেন্ট (Visa / MasterCard)', type: 'card', enabled: true, isDefault: false, order: 7 },
  { id: 'pay_own', name: 'মালিকের ব্যক্তিগত তহবিল (Owner Fund)', type: 'other', enabled: true, isDefault: false, order: 8 },
];

// Expense Categories
export const DEFAULT_EXPENSE_CATEGORIES: ExpenseCategoryItem[] = [
  { id: 'cat_rent', name: 'দোকান ও অফিস ভাড়া (Shop/Office Rent)', budgetMonthly: 20000, enabled: true },
  { id: 'cat_utility', name: 'বিদ্যুৎ, গ্যাস ও পানি বিল (Utility Bills)', budgetMonthly: 6000, enabled: true },
  { id: 'cat_salary', name: 'স্টাফ বেতন ও ভাতা (Staff Salary & Allowance)', budgetMonthly: 40000, enabled: true },
  { id: 'cat_transport', name: 'পরিবহন, কুলি ও লজিস্টিক (Transport & Freight)', budgetMonthly: 10000, enabled: true },
  { id: 'cat_tea', name: 'আপ্যায়ন ও নাস্তা খরচ (Entertainment & Food)', budgetMonthly: 4000, enabled: true },
  { id: 'cat_repair', name: 'মেরামত ও রক্ষণাবেক্ষণ (Repairs & Maintenance)', budgetMonthly: 5000, enabled: true },
  { id: 'cat_marketing', name: 'বিজ্ঞাপন ও প্রচারণা (Marketing & Promotion)', budgetMonthly: 8000, enabled: true },
  { id: 'cat_misc', name: 'বিবিধ আনুষঙ্গিক খরচ (Miscellaneous)', budgetMonthly: 5000, enabled: true },
];

// Tax & Discount Settings
export const DEFAULT_TAX_DISCOUNT_SETTINGS: TaxDiscountSettings = {
  taxEnabled: true,
  defaultTaxRate: 5,
  taxName: 'ভ্যাট (VAT / BIN)',
  discountEnabled: true,
  defaultDiscountType: 'fixed',
  maxDiscountPercent: 25,
  showDiscountInPos: true,
};

// Role Permissions
export const DEFAULT_ROLE_PERMISSIONS: UserRoleDefinition[] = [
  {
    id: 'admin',
    name: 'মালিক ও সুপার অ্যাডমিন (Admin / Owner)',
    description: 'পুরো সফটওয়্যারের সর্বময় নিয়ন্ত্রণ ও ফুল সেটিংস এক্সেস',
    canAccessSettings: true,
    permissions: [
      { module: 'dashboard', label: 'ড্যাশবোর্ড', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'sales', label: 'বিক্রয় ও ইনভয়েস', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'pos', label: 'POS বিলিং কাউন্টার', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'purchases', label: 'ক্রয় ও বিল', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'products', label: 'পণ্য ও স্টক ইনভেন্টরি', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'customers', label: 'কাস্টমার ও খাতা', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'suppliers', label: 'সাপ্লায়ার ও মহাজন', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'expenses', label: 'দৈনিক খরচ ও ভাউচার', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'payments', label: 'পেমেন্ট কালেকশন ও প্রদান', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'accounting', label: 'অ্যাকাউন্টিং ও খতিয়ান', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'hr', label: 'কর্মী ও বেতন শিট', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'reports', label: 'রিপোর্ট সেন্টার ও স্টেটমেন্ট', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
      { module: 'settings', label: 'কন্ট্রোল সেন্টার ও ব্যাকআপ', canView: true, canCreate: true, canEdit: true, canDelete: true, canPrint: true, canExport: true },
    ],
  },
  {
    id: 'manager',
    name: 'ম্যানেজার (Branch Manager)',
    description: 'দৈনন্দিন ব্যবসা পরিচালনা, পণ্য যুক্ত ও বিক্রয় অনুমোদন',
    canAccessSettings: false,
    permissions: [
      { module: 'dashboard', label: 'ড্যাশবোর্ড', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'sales', label: 'বিক্রয় ও ইনভয়েস', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'pos', label: 'POS বিলিং কাউন্টার', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'purchases', label: 'ক্রয় ও বিল', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'products', label: 'পণ্য ও স্টক ইনভেন্টরি', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'customers', label: 'কাস্টমার ও খাতা', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'suppliers', label: 'সাপ্লায়ার ও মহাজন', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'expenses', label: 'দৈনিক খরচ ও ভাউচার', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'payments', label: 'পেমেন্ট কালেকশন ও প্রদান', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'accounting', label: 'অ্যাকাউন্টিং ও খতিয়ান', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: true },
      { module: 'hr', label: 'কর্মী ও বেতন শিট', canView: true, canCreate: true, canEdit: false, canDelete: false, canPrint: true, canExport: true },
      { module: 'reports', label: 'রিপোর্ট সেন্টার ও স্টেটমেন্ট', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: true },
      { module: 'settings', label: 'কন্ট্রোল সেন্টার ও ব্যাকআপ', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
    ],
  },
  {
    id: 'accountant',
    name: 'হিসাবরক্ষক (Accountant)',
    description: 'আর্থিক লেনদেন, খরচ, পেমেন্ট ও রিপোর্ট অডিট',
    canAccessSettings: false,
    permissions: [
      { module: 'dashboard', label: 'ড্যাশবোর্ড', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: true },
      { module: 'sales', label: 'বিক্রয় ও ইনভয়েস', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: true },
      { module: 'pos', label: 'POS বিলিং কাউন্টার', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'purchases', label: 'ক্রয় ও বিল', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'products', label: 'পণ্য ও স্টক ইনভেন্টরি', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: true },
      { module: 'customers', label: 'কাস্টমার ও খাতা', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'suppliers', label: 'সাপ্লায়ার ও মহাজন', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'expenses', label: 'দৈনিক খরচ ও ভাউচার', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'payments', label: 'পেমেন্ট কালেকশন ও প্রদান', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'accounting', label: 'অ্যাকাউন্টিং ও খতিয়ান', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'hr', label: 'কর্মী ও বেতন শিট', canView: true, canCreate: true, canEdit: true, canDelete: false, canPrint: true, canExport: true },
      { module: 'reports', label: 'রিপোর্ট সেন্টার ও স্টেটমেন্ট', canView: true, canCreate: true, canEdit: false, canDelete: false, canPrint: true, canExport: true },
      { module: 'settings', label: 'কন্ট্রোল সেন্টার ও ব্যাকআপ', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
    ],
  },
  {
    id: 'sales',
    name: 'বিক্রয় প্রতিনিধি (Sales Executive)',
    description: 'নতুন বিক্রয় তৈরি, কাস্টমার খাতা দেখা ও কালেকশন এন্ট্রি',
    canAccessSettings: false,
    permissions: [
      { module: 'dashboard', label: 'ড্যাশবোর্ড', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'sales', label: 'বিক্রয় ও ইনভয়েস', canView: true, canCreate: true, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'pos', label: 'POS বিলিং কাউন্টার', canView: true, canCreate: true, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'purchases', label: 'ক্রয় ও বিল', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'products', label: 'পণ্য ও স্টক ইনভেন্টরি', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'customers', label: 'কাস্টমার ও খাতা', canView: true, canCreate: true, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'suppliers', label: 'সাপ্লায়ার ও মহাজন', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'expenses', label: 'দৈনিক খরচ ও ভাউচার', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'payments', label: 'পেমেন্ট কালেকশন ও প্রদান', canView: true, canCreate: true, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'accounting', label: 'অ্যাকাউন্টিং ও খতিয়ান', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'hr', label: 'কর্মী ও বেতন শিট', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'reports', label: 'রিপোর্ট সেন্টার ও স্টেটমেন্ট', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'settings', label: 'কন্ট্রোল সেন্টার ও ব্যাকআপ', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
    ],
  },
  {
    id: 'cashier',
    name: 'ক্যাশিয়ার (POS Cashier)',
    description: 'দ্রুত POS সেল, পেমেন্ট রিসিট প্রিন্ট ও শিফট ক্লোজিং',
    canAccessSettings: false,
    permissions: [
      { module: 'dashboard', label: 'ড্যাশবোর্ড', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'sales', label: 'বিক্রয় ও ইনভয়েস', canView: true, canCreate: true, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'pos', label: 'POS বিলিং কাউন্টার', canView: true, canCreate: true, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'purchases', label: 'ক্রয় ও বিল', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'products', label: 'পণ্য ও স্টক ইনভেন্টরি', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'customers', label: 'কাস্টমার ও খাতা', canView: true, canCreate: true, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'suppliers', label: 'সাপ্লায়ার ও মহাজন', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'expenses', label: 'দৈনিক খরচ ও ভাউচার', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'payments', label: 'পেমেন্ট কালেকশন ও প্রদান', canView: true, canCreate: true, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'accounting', label: 'অ্যাকাউন্টিং ও খতিয়ান', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'hr', label: 'কর্মী ও বেতন শিট', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'reports', label: 'রিপোর্ট সেন্টার ও স্টেটমেন্ট', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'settings', label: 'কন্ট্রোল সেন্টার ও ব্যাকআপ', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
    ],
  },
  {
    id: 'viewer',
    name: 'দর্শক (Read-Only Viewer)',
    description: 'শুধুমাত্র রিপোর্ট ও স্টেটমেন্ট দেখার অধিকার',
    canAccessSettings: false,
    permissions: [
      { module: 'dashboard', label: 'ড্যাশবোর্ড', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'sales', label: 'বিক্রয় ও ইনভয়েস', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'pos', label: 'POS বিলিং কাউন্টার', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
      { module: 'purchases', label: 'ক্রয় ও বিল', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'products', label: 'পণ্য ও স্টক ইনভেন্টরি', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'customers', label: 'কাস্টমার ও খাতা', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'suppliers', label: 'সাপ্লায়ার ও মহাজন', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'expenses', label: 'দৈনিক খরচ ও ভাউচার', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'payments', label: 'পেমেন্ট কালেকশন ও প্রদান', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'accounting', label: 'অ্যাকাউন্টিং ও খতিয়ান', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'hr', label: 'কর্মী ও বেতন শিট', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: false },
      { module: 'reports', label: 'রিপোর্ট সেন্টার ও স্টেটমেন্ট', canView: true, canCreate: false, canEdit: false, canDelete: false, canPrint: true, canExport: true },
      { module: 'settings', label: 'কন্ট্রোল সেন্টার ও ব্যাকআপ', canView: false, canCreate: false, canEdit: false, canDelete: false, canPrint: false, canExport: false },
    ],
  },
];

// General Localization
export const DEFAULT_LOCALIZATION_SETTINGS: LocalizationSettings = {
  language: 'bn',
  currencySymbol: '৳',
  currencyPosition: 'before',
  dateFormat: 'YYYY-MM-DD',
  timeFormat: '12h',
  numberFormat: 'bangladeshi',
  timezone: 'Asia/Dhaka',
};

// Notification Settings
export const DEFAULT_NOTIFICATION_SETTINGS: NotificationSettings = {
  newSale: true,
  newPurchase: true,
  paymentReceived: true,
  duePaymentAlert: true,
  expenseAdded: true,
  lowStockAlert: true,
  systemAlert: true,
  soundEnabled: true,
};

// Security & Recovery Settings
export const DEFAULT_SECURITY_SETTINGS: SecuritySettings = {
  adminPin: '1234',
  recoveryEmail: 'alluser27bd@gmail.com',
  isRecoveryEmailVerified: true,
  recoveryPhone: '01711-234567',
  isRecoveryPhoneVerified: true,
  backupCodes: [
    'BIZ-8924-1182',
    'BIZ-5731-9043',
    'BIZ-3219-4401',
    'BIZ-7650-8829',
    'BIZ-4108-6593',
    'BIZ-9342-7015',
    'BIZ-1845-6670',
    'BIZ-6029-3318',
  ],
  usedBackupCodes: [],
  maxFailedAttempts: 5,
  lockoutDurationMinutes: 5,
  failedAttemptsCount: 0,
  lockoutUntil: null,
  requirePinForDelete: true,
  requirePinForBackup: false,
  requirePinForReset: true,
  autoLogoutMinutes: 0,
  showActivityLog: true,
  securityLogs: [
    {
      id: 'SEC-LOG-001',
      timestamp: '2026-03-29 10:00:00',
      type: 'account_created',
      description: 'অ্যাডমিন অ্যাকাউন্ট তৈরি ও জিমেইল ভেরিফিকেশন সফল হয়েছে (alluser27bd@gmail.com)',
      ipOrDevice: 'Chrome (Desktop)',
      status: 'success',
    },
    {
      id: 'SEC-LOG-002',
      timestamp: '2026-03-29 10:05:00',
      type: 'backup_codes_generated',
      description: '৮টি নিরাপদ ব্যাকআপ রিকভারি কোড জেনারেট করা হয়েছে',
      ipOrDevice: 'Security Hub',
      status: 'success',
    },
  ],
};

// 13. Master Data & Business Setup Defaults
export const DEFAULT_BUSINESS_SETUP: BusinessSetupConfig = {
  businessName: 'মেসার্স ভাই ভাই এন্টারপ্রাইজ (Vai Vai Enterprise)',
  businessType: 'হোলসেল ও রিটেইল ট্রেডার্স এবং সাপ্লাইয়ার্স',
  shopType: 'মুদি, চাল ও খাদ্যশস্য সুপারশপ',
  businessCategory: 'খাদ্য ও ভোগ্যপণ্য (FMCG & Groceries)',
  businessDescription: 'উচ্চমানের চাল, ভোজ্যতেল, চিনি ও খাদ্যশস্য পাইকারি ও খুচরা সরবরাহকারী।',
  branches: [
    {
      id: 'BR-01',
      name: 'প্রধান শাখা ও শোরুম (Main Branch)',
      code: 'MAIN-01',
      address: 'দোকান নং ১২, নিউ মার্কেট রোড, ঢাকা-১২০৫',
      phone: '+880 1711-234567',
      isDefault: true,
      isActive: true,
    },
    {
      id: 'BR-02',
      name: 'চকবাজার হোলসেল আউটলেট',
      code: 'CHOK-02',
      address: 'চক সার্কুলার রোড, চকবাজার, ঢাকা',
      phone: '+880 1819-876543',
      isDefault: false,
      isActive: true,
    },
  ],
  businessTypesList: [
    'হোলসেল ও রিটেইল ট্রেডার্স এবং সাপ্লাইয়ার্স',
    'খুচরা দোকান ও সুপারশপ (Retail / Super Shop)',
    'পাইকারি আড়ত ও ডিস্ট্রিবিউশন (Wholesale & Distribution)',
    'ফার্মেসি ও ড্রাগ স্টোর (Pharmacy / Healthcare)',
    'গার্মেন্টস ও ফ্যাশন হাউস (Garments & Apparel)',
    'ইলেকট্রনিক্স ও হার্ডওয়্যার (Electronics & Hardware)',
    'উৎপাদন ও কারখানা (Manufacturing / Factory)',
    'রেস্তোরাঁ ও ক্যাফে (Restaurant & Cafe)',
  ],
  shopTypesList: [
    'মুদি, চাল ও খাদ্যশস্য সুপারশপ',
    'ডিপার্টমেন্টাল স্টোর',
    'কনজিউমার গুডস ডিলারশিপ',
    'পাইকারি ভোজ্যতেল ও ডাল আড়ত',
    'ড্রাগ অ্যান্ড মেডিসিন শপ',
    'কম্পিউটার ও মোবাইল শোরুম',
  ],
  businessCategoriesList: [
    'খাদ্য ও ভোগ্যপণ্য (FMCG & Groceries)',
    'কৃষি ও খাদ্যশস্য (Agro & Crops)',
    'মেডিসিন ও হেলথকেয়ার (Healthcare)',
    'ইলেকট্রনিক্স ও গ্যাজেট (Electronics)',
    'পোশাক ও ফ্যাশন (Apparel & Fashion)',
    'বিল্ডিং ম্যাটেরিয়ালস (Building & Hardware)',
  ],
};

export const DEFAULT_BRANDS_LIST: BrandItem[] = [
  { id: 'BRD-001', name: 'রূপচাঁদা (Rupchanda)', code: 'RUP', description: 'প্রিমিয়াম ভোজ্যতেল ব্র্যান্ড', isActive: true, order: 1 },
  { id: 'BRD-002', name: 'ফার্মার্স গোল্ড (Farmer\'s Gold)', code: 'FG', description: 'উচ্চমানের চাল ও খাদ্যশস্য', isActive: true, order: 2 },
  { id: 'BRD-003', name: 'দাওয়াত (Daawat)', code: 'DWT', description: 'সুগন্ধি বাসমতি চাল', isActive: true, order: 3 },
  { id: 'BRD-004', name: 'তীর (Teer)', code: 'TEER', description: 'আটা, ময়দা, সুজি ও তেল', isActive: true, order: 4 },
  { id: 'BRD-005', name: 'ফ্রেশ (Fresh - Meghna Group)', code: 'FRSH', description: 'মেঘনা গ্রুপের পণ্যসামগ্রী', isActive: true, order: 5 },
  { id: 'BRD-006', name: 'প্রাণ (PRAN)', code: 'PRAN', description: 'প্রসেসড ফুড ও বেভারেজ', isActive: true, order: 6 },
  { id: 'BRD-007', name: 'এসিআই পিওর (ACI Pure)', code: 'ACI', description: 'লবণ, চাল ও মশলা', isActive: true, order: 7 },
  { id: 'BRD-008', name: 'দেশী চিনি (Local Sugar)', code: 'DSUG', description: 'দেশী মিল চিনি', isActive: true, order: 8 },
];

export const DEFAULT_CATEGORIES_LIST: CategoryItem[] = [
  {
    id: 'CAT-001',
    name: 'ভোজ্যতেল ও ঘি (Edible Oil & Ghee)',
    code: 'OIL',
    description: 'সয়াবিন, সরিষা, পাম অয়েল ও ঘি',
    subcategories: ['সয়াবিন তেল', 'সরিষার তেল', 'ঘি ও মাখন', 'পাম অয়েল'],
    isActive: true,
    order: 1,
  },
  {
    id: 'CAT-002',
    name: 'চাল ও খাদ্যশস্য (Rice & Grains)',
    code: 'RICE',
    description: 'মিনিকেট, নাজিরশাইল, বাসমতি ও পোলাও চাল',
    subcategories: ['মিনিকেট চাল', 'বাসমতি চাল', 'নাজিরশাইল', 'সুগন্ধি পোলাও চাল', 'আটা ও ময়দা'],
    isActive: true,
    order: 2,
  },
  {
    id: 'CAT-003',
    name: 'মুদি মালামাল ও মসলা (Groceries & Spices)',
    code: 'GROC',
    description: 'চিনি, লবণ, ডাল, হলুদ, মরিচ ও গরম মশলা',
    subcategories: ['চিনি ও মিষ্টিদ্রব্য', 'লবণ', 'মসুর ডাল', 'ছোলা ও বুট', 'গুঁড়া মশলা'],
    isActive: true,
    order: 3,
  },
  {
    id: 'CAT-004',
    name: 'কাঁচামাল ও প্যাকেজিং (Raw Material & Packaging)',
    code: 'RAW',
    description: 'উৎপাদন ও মোড়কীকরণের সামগ্রী',
    subcategories: ['প্যাকেজিং বক্স কার্টন', 'প্লাস্টিক জার', 'লেবেল স্টিকার'],
    isActive: true,
    order: 4,
  },
  {
    id: 'CAT-005',
    name: 'বেভারেজ ও জুস (Beverage & Juice)',
    code: 'BEV',
    description: 'কোমল পানীয়, চা পাতা, কফি ও ফলের জুস',
    subcategories: ['চা পাতা', 'কফি', 'জুস ও ড্রিংকস'],
    isActive: true,
    order: 5,
  },
];

export const DEFAULT_UNITS_LIST: UnitItem[] = [
  { id: 'UNT-001', name: 'কেজি (kg)', code: 'kg', description: 'কিলোগ্রাম ওজন পরিমাপ', isActive: true, order: 1 },
  { id: 'UNT-002', name: 'লিটার (ltr)', code: 'ltr', description: 'তরল আয়তন পরিমাপ', isActive: true, order: 2 },
  { id: 'UNT-003', name: 'ব্যাগ (bag / ২৫/৫০ কেজি)', code: 'bag', description: 'বস্তা বা বস্তাজাত খাদ্য', isActive: true, order: 3 },
  { id: 'UNT-004', name: 'পিস / সংখ্যা (pcs)', code: 'pcs', description: 'একক গণনাযোগ্য পণ্য', isActive: true, order: 4 },
  { id: 'UNT-005', name: 'বক্স (box)', code: 'box', description: 'ছোট মোড়ক বাক্স', isActive: true, order: 5 },
  { id: 'UNT-006', name: 'কার্টন (carton)', code: 'carton', description: 'মাস্টার কার্টন কেস', isActive: true, order: 6 },
  { id: 'UNT-007', name: 'গ্রাম (gm)', code: 'gm', description: 'ক্ষুদ্র ওজন পরিমাপ', isActive: true, order: 7 },
  { id: 'UNT-008', name: 'টন (ton)', code: 'ton', description: '১০০০ কেজি পাইকারি চালান', isActive: true, order: 8 },
  { id: 'UNT-009', name: 'মিটার (meter)', code: 'meter', description: 'দৈর্ঘ্য পরিমাপ', isActive: true, order: 9 },
  { id: 'UNT-010', name: 'প্যাকেট (packet)', code: 'packet', description: 'ছোট খুচরা প্যাকেট', isActive: true, order: 10 },
];

export const DEFAULT_PRODUCT_TYPES_LIST: ProductTypeItem[] = [
  { id: 'PT-01', name: 'ফিনিশড পণ্য (Finished Goods)', code: 'finished', isActive: true },
  { id: 'PT-02', name: 'কাঁচামাল (Raw Material)', code: 'raw_material', isActive: true },
  { id: 'PT-03', name: 'কম্বো / প্যাকেজ (Combo Pack)', code: 'combo', isActive: true },
  { id: 'PT-04', name: 'সার্ভিস / সেবা (Service)', code: 'service', isActive: true },
  { id: 'PT-05', name: 'ডিজিটাল প্রোডাক্ট (Digital Item)', code: 'digital', isActive: true },
];

export const DEFAULT_PRODUCT_STATUS_LIST: ProductStatusItem[] = [
  { id: 'PS-01', name: 'পর্যাপ্ত মজুদ (In Stock)', color: 'emerald', isActive: true },
  { id: 'PS-02', name: 'মজুদ স্বল্পতা (Low Stock)', color: 'amber', isActive: true },
  { id: 'PS-03', name: 'স্টক শেষ (Out of Stock)', color: 'rose', isActive: true },
  { id: 'PS-04', name: 'সাময়িক স্থগিত (Discontinued)', color: 'slate', isActive: true },
];

export const DEFAULT_TAX_TYPES_LIST: TaxTypeItem[] = [
  { id: 'TAX-00', name: 'ট্যাক্স মুক্ত / ০% ভ্যাট (Zero VAT)', rate: 0, isDefault: true, isActive: true },
  { id: 'TAX-05', name: '৫% স্ট্যান্ডার্ড পণ্য ভ্যাট (5% VAT)', rate: 5, isDefault: false, isActive: true },
  { id: 'TAX-75', name: '৭.৫% খুচরা ভ্যাট (7.5% VAT)', rate: 7.5, isDefault: false, isActive: true },
  { id: 'TAX-15', name: '১৫% স্ট্যান্ডার্ড ভ্যাট (15% VAT)', rate: 15, isDefault: false, isActive: true },
];

export const DEFAULT_DISCOUNT_TYPES_LIST: DiscountTypeItem[] = [
  { id: 'DISC-01', name: 'শতাংশ ছাড় (Percentage %)', type: 'percentage', isDefault: true, isActive: true },
  { id: 'DISC-02', name: 'নির্দিষ্ট নগদ ছাড় (Flat Cash ৳)', type: 'fixed', isDefault: false, isActive: true },
  { id: 'DISC-03', name: 'ভলিউম পাইকারি ডিসকাউন্ট', type: 'percentage', isDefault: false, isActive: true },
  { id: 'DISC-04', name: 'উৎসব / স্পেশাল অফার', type: 'fixed', isDefault: false, isActive: true },
];

export const DEFAULT_PRICE_TYPES_LIST: PriceTypeItem[] = [
  { id: 'PRC-01', name: 'সর্বোচ্চ খুচরা মূল্য (Retail MRP)', code: 'mrp', isActive: true },
  { id: 'PRC-02', name: 'পাইকারি রেট (Wholesale Rate)', code: 'wholesale', isActive: true },
  { id: 'PRC-03', name: 'ডিলার / এজেন্সি দর (Dealer Price)', code: 'dealer', isActive: true },
  { id: 'PRC-04', name: 'ভিআইপি / স্পেশাল গ্রাহক দর', code: 'vip', isActive: true },
];

export const DEFAULT_INCOME_CATEGORIES_LIST: IncomeCategoryItem[] = [
  { id: 'INC-01', name: 'পণ্য বিক্রয় থেকে আয় (Sales Revenue)', isActive: true },
  { id: 'INC-02', name: 'স্ক্র্যাপ / বর্জ্য ও খালি বস্তা বিক্রি', isActive: true },
  { id: 'INC-03', name: 'হোম ডেলিভারি সার্ভিস চার্জ আয়', isActive: true },
  { id: 'INC-04', name: 'কমিশন ও ইনসেন্টিভ প্রাপ্তি', isActive: true },
  { id: 'INC-05', name: 'মালিকের অতিরিক্ত বিনিয়োগ (Capital Added)', isActive: true },
];

export const DEFAULT_CUSTOMER_TYPES_LIST: CustomerTypeItem[] = [
  { id: 'CT-01', name: 'সাধারণ খুচরা কাস্টমার (Retail)', discountPercent: 0, isActive: true },
  { id: 'CT-02', name: 'নিয়মিত পাইকারি গ্রাহক (Wholesale)', discountPercent: 2, isActive: true },
  { id: 'CT-03', name: 'করপোরেট প্রতিষ্ঠান / সুপারশপ', discountPercent: 3, isActive: true },
  { id: 'CT-04', name: 'ডিলার ও সাব-ডিস্ট্রিবিউটর', discountPercent: 5, isActive: true },
];

export const DEFAULT_SUPPLIER_TYPES_LIST: SupplierTypeItem[] = [
  { id: 'ST-01', name: 'ম্যানুফ্যাকচারার / মিল (Manufacturer)', isActive: true },
  { id: 'ST-02', name: 'আমদানিকারক প্রতিষ্ঠান (Direct Importer)', isActive: true },
  { id: 'ST-03', name: 'প্রধান ডিস্ট্রিবিউটর ও কর্পোরেশন', isActive: true },
  { id: 'ST-04', name: 'স্থানীয় পাইকারি আড়তদার (Local Wholesaler)', isActive: true },
  { id: 'ST-05', name: 'কাঁচামাল ও প্যাকেজিং সাপ্লাইয়ার', isActive: true },
];

export const DEFAULT_SALES_TYPES_LIST: SalesTypeItem[] = [
  { id: 'SLT-01', name: 'নগদ বিক্রয় চালান (Cash Sale)', isActive: true },
  { id: 'SLT-02', name: 'বাকি বিক্রয় চালান (Credit Sale)', isActive: true },
  { id: 'SLT-03', name: 'কাউন্টার পিওএস দ্রুত বিক্রয় (POS Counter)', isActive: true },
  { id: 'SLT-04', name: 'অনলাইন ও ডেলিভারি অর্ডার (Delivery Order)', isActive: true },
  { id: 'SLT-05', name: 'পাইকারি বাল্ক চালান (Wholesale Invoice)', isActive: true },
];

export const DEFAULT_PURCHASE_TYPES_LIST: PurchaseTypeItem[] = [
  { id: 'PRT-01', name: 'সরাসরি নগদ ক্রয় (Cash Purchase)', isActive: true },
  { id: 'PRT-02', name: 'বাকিতে মহাজন ক্রয় বিল (Credit Bill)', isActive: true },
  { id: 'PRT-03', name: 'আমদানি এলসি চালান (Import LC)', isActive: true },
  { id: 'PRT-04', name: 'ফ্যাক্টরি কাঁচামাল চালান (Raw Material Inward)', isActive: true },
];

// 14. Top & Down Icon Menu Control & Customization Defaults
export const DEFAULT_TOP_ICON_MENU_ITEMS: TopIconMenuItem[] = [
  // --- Top Menu Bar Items ---
  {
    id: 'btn-sync',
    label: 'সেন্ট্রাল সিঙ্ক',
    subLabel: 'Database Live Sync',
    iconName: 'RefreshCw',
    actionType: 'modal',
    target: 'sync',
    location: 'top',
    color: 'emerald',
    badgeType: 'dot',
    isVisible: true,
    order: 1,
    showOnMobile: false,
    showLabelOnDesktop: true,
    tooltip: 'সেন্ট্রাল ডাটাবেস লাইভ সিঙ্ক',
    isSystem: true,
  },
  {
    id: 'btn-quick',
    label: 'কুইক অ্যাকশন',
    subLabel: 'Quick Add Menu',
    iconName: 'PlusCircle',
    actionType: 'modal',
    target: 'quickAction',
    location: 'top',
    color: 'emerald',
    isVisible: true,
    order: 2,
    showOnMobile: true,
    showLabelOnDesktop: true,
    tooltip: 'দ্রুত বিক্রয়, ক্রয় ও খরচ যুক্ত করুন',
    isSystem: true,
  },
  {
    id: 'btn-pos',
    label: 'পিওএস কাউন্টার',
    subLabel: 'POS Fast Counter',
    iconName: 'ShoppingCart',
    actionType: 'tab',
    target: 'pos',
    location: 'top',
    color: 'emerald',
    isVisible: true,
    order: 3,
    showOnMobile: true,
    showLabelOnDesktop: false,
    tooltip: 'দ্রুত পিওএস ক্যাশ কাউন্টারে যান',
  },
  {
    id: 'btn-shift',
    label: 'ক্যাশিয়ার শিফট',
    subLabel: 'Shift & Cash Drawer',
    iconName: 'Clock',
    actionType: 'modal',
    target: 'shiftModal',
    location: 'top',
    color: 'amber',
    isVisible: true,
    order: 4,
    showOnMobile: false,
    showLabelOnDesktop: true,
    tooltip: 'ক্যাশিয়ার শিফট ও ড্রয়ার ব্যালেন্স',
    isSystem: true,
  },
  {
    id: 'btn-approvals',
    label: 'অনুমোদন কিউ',
    subLabel: 'Pending Approvals',
    iconName: 'Bell',
    actionType: 'tab',
    target: 'approvals',
    location: 'top',
    color: 'rose',
    badgeType: 'count',
    isVisible: true,
    order: 5,
    showOnMobile: true,
    showLabelOnDesktop: false,
    tooltip: 'অ্যাডমিন অনুমোদন কিউ',
    isSystem: true,
  },
  {
    id: 'btn-backup',
    label: 'ক্লাউড ব্যাকআপ',
    subLabel: 'Auto Backup Status',
    iconName: 'HardDrive',
    actionType: 'modal',
    target: 'backupModal',
    location: 'top',
    color: 'emerald',
    badgeType: 'dot',
    isVisible: true,
    order: 6,
    showOnMobile: false,
    showLabelOnDesktop: true,
    tooltip: 'অটো ক্লাউড ব্যাকআপ সেটিংস ও স্ন্যাপশট',
    isSystem: true,
  },
  {
    id: 'btn-gmail',
    label: 'জিমেইল সিঙ্ক',
    subLabel: 'Gmail Account',
    iconName: 'Mail',
    actionType: 'modal',
    target: 'gmailModal',
    location: 'top',
    color: 'slate',
    isVisible: true,
    order: 7,
    showOnMobile: false,
    showLabelOnDesktop: true,
    tooltip: 'জিমেইল অ্যাকাউন্ট ও ড্রাইভ স্টোরেজ',
    isSystem: true,
  },
  {
    id: 'btn-role',
    label: 'রোল পরিবর্তন',
    subLabel: 'Role Switcher',
    iconName: 'ShieldCheck',
    actionType: 'modal',
    target: 'role',
    location: 'top',
    color: 'slate',
    isVisible: true,
    order: 8,
    showOnMobile: true,
    showLabelOnDesktop: true,
    tooltip: 'ইউজার রোল পারমিশন পরিবর্তন',
    isSystem: true,
  },
  {
    id: 'btn-text',
    label: 'ফন্ট সাইজ',
    subLabel: 'Text Size Zoom',
    iconName: 'Type',
    actionType: 'modal',
    target: 'textSize',
    location: 'top',
    color: 'slate',
    isVisible: true,
    order: 9,
    showOnMobile: true,
    showLabelOnDesktop: true,
    tooltip: 'টেক্সট ফন্ট সাইজ বড়/ছোট করুন',
    isSystem: true,
  },
  {
    id: 'btn-sale',
    label: 'নতুন বিক্রয়',
    subLabel: 'Create Sale Invoice',
    iconName: 'Receipt',
    actionType: 'tab',
    target: 'sales',
    location: 'top',
    color: 'blue',
    isVisible: false,
    order: 10,
    showOnMobile: false,
    showLabelOnDesktop: true,
    tooltip: 'নতুন সেলস চালান তৈরি',
  },
  {
    id: 'btn-purchase',
    label: 'নতুন ক্রয়',
    subLabel: 'Create Purchase Bill',
    iconName: 'Package',
    actionType: 'tab',
    target: 'purchases',
    location: 'top',
    color: 'amber',
    isVisible: false,
    order: 11,
    showOnMobile: false,
    showLabelOnDesktop: true,
    tooltip: 'নতুন ক্রয় চালান তৈরি',
  },
  {
    id: 'btn-expenses',
    label: 'দৈনিক খরচ',
    subLabel: 'Expense Entry',
    iconName: 'Wallet',
    actionType: 'tab',
    target: 'expenses',
    location: 'top',
    color: 'rose',
    isVisible: false,
    order: 12,
    showOnMobile: false,
    showLabelOnDesktop: true,
    tooltip: 'দৈনিক খরচ এন্ট্রি',
  },
  {
    id: 'btn-calculator',
    label: 'ক্যালকুলেটর',
    subLabel: 'Quick Calculator',
    iconName: 'Calculator',
    actionType: 'custom_action',
    target: 'calculator',
    location: 'top',
    color: 'purple',
    isVisible: false,
    order: 13,
    showOnMobile: false,
    showLabelOnDesktop: false,
    tooltip: 'কুইক ক্যালকুলেটর পপআপ',
  },
  {
    id: 'btn-fullscreen',
    label: 'ফুলস্ক্রিন',
    subLabel: 'Toggle Fullscreen',
    iconName: 'Maximize',
    actionType: 'custom_action',
    target: 'fullscreen',
    location: 'top',
    color: 'cyan',
    isVisible: false,
    order: 14,
    showOnMobile: false,
    showLabelOnDesktop: false,
    tooltip: 'ফুল স্ক্রিন মোড চালু/বন্ধ',
  },
  {
    id: 'btn-reports',
    label: 'রিপোর্ট সেন্টার',
    subLabel: 'Analytics & Reports',
    iconName: 'BarChart3',
    actionType: 'tab',
    target: 'reports',
    location: 'top',
    color: 'indigo',
    isVisible: false,
    order: 15,
    showOnMobile: false,
    showLabelOnDesktop: true,
    tooltip: 'সকল ব্যবসায়িক হিসাব রিপোর্ট',
  },
  {
    id: 'btn-recycle',
    label: 'রিসাইকেল বিন',
    subLabel: 'Recycle Bin',
    iconName: 'Trash2',
    actionType: 'tab',
    target: 'recyclebin',
    location: 'top',
    color: 'slate',
    isVisible: false,
    order: 16,
    showOnMobile: false,
    showLabelOnDesktop: false,
    tooltip: 'মুছে ফেলা তথ্যের রিসাইকেল বিন',
  },
  {
    id: 'btn-settings',
    label: 'সেটিংস কন্ট্রোল',
    subLabel: 'System Settings',
    iconName: 'Settings',
    actionType: 'tab',
    target: 'settings',
    location: 'top',
    color: 'emerald',
    isVisible: false,
    order: 17,
    showOnMobile: false,
    showLabelOnDesktop: false,
    tooltip: 'সফটওয়্যার সেটিংস ও মাস্টার ডাটা',
  },

  // --- Down / Bottom Navigation Menu Items ---
  {
    id: 'btm-dashboard',
    label: 'হোম',
    subLabel: 'Home Dashboard',
    iconName: 'Store',
    actionType: 'tab',
    target: 'dashboard',
    location: 'bottom',
    color: 'emerald',
    isVisible: true,
    order: 1,
    showOnMobile: true,
    showLabelOnDesktop: true,
    tooltip: 'হোম ড্যাশবোর্ড',
  },
  {
    id: 'btm-pos',
    label: 'শপ/POS',
    subLabel: 'POS Fast Counter',
    iconName: 'ShoppingCart',
    actionType: 'tab',
    target: 'pos',
    location: 'bottom',
    color: 'emerald',
    isVisible: true,
    order: 2,
    showOnMobile: true,
    showLabelOnDesktop: true,
    tooltip: 'পিওএস বিক্রয় কাউন্টার',
  },
  {
    id: 'btm-sales',
    label: 'বিক্রয়',
    subLabel: 'Sales Invoices',
    iconName: 'Receipt',
    actionType: 'tab',
    target: 'sales',
    location: 'bottom',
    color: 'blue',
    isVisible: true,
    order: 3,
    showOnMobile: true,
    showLabelOnDesktop: true,
    tooltip: 'বিক্রয় ও চালান খাতা',
  },
  {
    id: 'btm-reports',
    label: 'রিপোর্ট',
    subLabel: 'Financial Reports',
    iconName: 'BarChart3',
    actionType: 'tab',
    target: 'reports',
    location: 'bottom',
    color: 'purple',
    isVisible: true,
    order: 4,
    showOnMobile: true,
    showLabelOnDesktop: true,
    tooltip: 'ব্যবসায়িক রিপোর্ট ও লাভ-ক্ষতি',
  },
  {
    id: 'btm-more',
    label: 'মেনু',
    subLabel: 'All Modules Drawer',
    iconName: 'MoreHorizontal',
    actionType: 'modal',
    target: 'mobileMenu',
    location: 'bottom',
    color: 'slate',
    isVisible: true,
    order: 5,
    showOnMobile: true,
    showLabelOnDesktop: true,
    tooltip: 'সকল মডিউলের ড্রয়ার মেনু',
    isSystem: true,
  },
];

export const DEFAULT_TOP_ICON_MENU_CONFIG: TopIconMenuConfig = {
  isEnabled: true,
  placement: 'top_navbar_right',
  alignment: 'end',
  spacing: 'standard',
  buttonStyle: 'rounded_icon_button',
  iconSize: 'medium',
  showLabels: true,
  bottomPlacement: 'fixed_bottom',
  showBottomOnDesktop: false,
  bottomSpacing: 'standard',
  bottomButtonStyle: 'native_nav_tab',
  bottomIconSize: 'medium',
  items: DEFAULT_TOP_ICON_MENU_ITEMS,
};



