import React from 'react';
import {
  ShoppingCart,
  Receipt,
  Package,
  Boxes,
  Users,
  DollarSign,
  Wallet,
  CreditCard,
  Clock,
  Bell,
  HardDrive,
  ShieldCheck,
  Mail,
  RefreshCw,
  Type,
  Search,
  PlusCircle,
  Sparkles,
  Sliders,
  SlidersHorizontal,
  Calculator,
  Maximize,
  Minimize,
  Printer,
  FileText,
  BarChart3,
  TrendingUp,
  Store,
  Briefcase,
  Pill,
  Factory,
  Truck,
  Database,
  Trash2,
  Globe,
  Heart,
  Star,
  Compass,
  Zap,
  HelpCircle,
  Layers,
  FolderTree,
  Scale,
  Percent,
  CheckCircle2,
  AlertTriangle,
  PlayCircle,
  Eye,
  EyeOff,
  Lock,
  Key,
  Smartphone,
  FileSpreadsheet,
  History,
  Award,
  BookOpen,
  Send,
  UserCheck,
  Flame,
  Tag,
  Building2,
  Cpu,
  Monitor,
  Calendar,
  Gift,
  QrCode,
  ScanLine,
  Phone,
  Settings,
  CircleDot,
  Check,
  X,
  Share2,
  Download,
  Upload,
  Camera,
  Coins,
  ArrowRight,
  ChevronDown,
} from 'lucide-react';

export const ICON_REGISTRY: Record<string, React.ElementType> = {
  ShoppingCart,
  Receipt,
  Package,
  Boxes,
  Users,
  DollarSign,
  Wallet,
  CreditCard,
  Clock,
  Bell,
  HardDrive,
  ShieldCheck,
  Mail,
  RefreshCw,
  Type,
  Search,
  PlusCircle,
  Sparkles,
  Sliders,
  SlidersHorizontal,
  Calculator,
  Maximize,
  Minimize,
  Printer,
  FileText,
  BarChart3,
  TrendingUp,
  Store,
  Briefcase,
  Pill,
  Factory,
  Truck,
  Database,
  Trash2,
  Globe,
  Heart,
  Star,
  Compass,
  Zap,
  HelpCircle,
  Layers,
  FolderTree,
  Scale,
  Percent,
  CheckCircle2,
  AlertTriangle,
  PlayCircle,
  Eye,
  EyeOff,
  Lock,
  Key,
  Smartphone,
  FileSpreadsheet,
  History,
  Award,
  BookOpen,
  Send,
  UserCheck,
  Flame,
  Tag,
  Building2,
  Cpu,
  Monitor,
  Calendar,
  Gift,
  QrCode,
  ScanLine,
  Phone,
  Settings,
  CircleDot,
  Check,
  X,
  Share2,
  Download,
  Upload,
  Camera,
  Coins,
  ArrowRight,
  ChevronDown,
};

export const AVAILABLE_ICON_NAMES = Object.keys(ICON_REGISTRY);

export const getIconComponent = (iconName: string): React.ElementType => {
  return ICON_REGISTRY[iconName] || Tag;
};

export const COLOR_PALETTE = [
  { id: 'emerald', label: 'Emerald Green', bg: 'bg-emerald-50 text-emerald-800 border-emerald-200 hover:bg-emerald-100', text: 'text-emerald-600', dot: 'bg-emerald-500' },
  { id: 'blue', label: 'Ocean Blue', bg: 'bg-blue-50 text-blue-800 border-blue-200 hover:bg-blue-100', text: 'text-blue-600', dot: 'bg-blue-500' },
  { id: 'amber', label: 'Amber Gold', bg: 'bg-amber-50 text-amber-800 border-amber-200 hover:bg-amber-100', text: 'text-amber-600', dot: 'bg-amber-500' },
  { id: 'purple', label: 'Royal Purple', bg: 'bg-purple-50 text-purple-800 border-purple-200 hover:bg-purple-100', text: 'text-purple-600', dot: 'bg-purple-500' },
  { id: 'rose', label: 'Rose Red', bg: 'bg-rose-50 text-rose-800 border-rose-200 hover:bg-rose-100', text: 'text-rose-600', dot: 'bg-rose-500' },
  { id: 'slate', label: 'Modern Slate', bg: 'bg-slate-100 text-slate-800 border-slate-200 hover:bg-slate-200', text: 'text-slate-700', dot: 'bg-slate-500' },
  { id: 'indigo', label: 'Deep Indigo', bg: 'bg-indigo-50 text-indigo-800 border-indigo-200 hover:bg-indigo-100', text: 'text-indigo-600', dot: 'bg-indigo-500' },
  { id: 'teal', label: 'Teal Cyan', bg: 'bg-teal-50 text-teal-800 border-teal-200 hover:bg-teal-100', text: 'text-teal-600', dot: 'bg-teal-500' },
  { id: 'cyan', label: 'Sky Cyan', bg: 'bg-cyan-50 text-cyan-800 border-cyan-200 hover:bg-cyan-100', text: 'text-cyan-600', dot: 'bg-cyan-500' },
];
